### ISSUE TITLE
Question: how is the the field "lessonid" used in table "words"

### ISSUE THREAD

**Issue by GregVial** [migusta/coMNISTv2#13]
I am unsure how the field "lessonid" is used in table "words".
I initally thought this is how the application knows which words it can show at each lesson. 
But actually I also thought it was choosing words based on lessons completed by user (i.e. which letters it has learnt), therefore I am confused now :)

**Comment by migusta** [comment]
It isn't used now, just didn't delete it for now because of previous versions. Just leave it NULL now
