### ISSUE TITLE
Medium - Add additional input: "nb_output" and additional input: "correct"

### ISSUE THREAD

**Issue by GregVial** [migusta/coMNISTv2#4]
In order to be more flexible, the took should accept letters not perfectly formed.
For instance O and D can be easily mistaken.

The engine now predicts not the most likely letter, but the n most likely letters.
If nb_output is set to 1, then the engine will behave as previously
if nb_output is set to 2 or more, then it will provide more flexibility
Recommandation is to set the value to 2

Also, the engine will return the most likely word recognized, but in case nb_output > 1, the word may be accepted even if not matching exactly the expectet output.
For instance, if expected="WORD" but read = WDRD", then if nb_output is set to 2 and the second letter is predicted as either D or O, then although the predicted word will be different from  expected, "correct" will be set to 1, which means success.

**Comment by migusta** [comment]
will appear with the new commit
