### ISSUE TITLE
Low: new logo and title

### ISSUE THREAD

**Issue by GregVial** [migusta/coMNISTv2#5]
As per learn2write.gregvi.al:
- Use different (temporary) logo with link to your github. Need to get a better logo one but this will do for demo day :)
- Use head/title "learn2write, learning a new alphabet made easy" instead of "comnist..."
- Remove sentence after logo

Would be nice to add a banner at the bottom "powered by " and then comnist logo with link to github.com/GregVial/CoMNIST

**Comment by migusta** [comment]
In the new commit
